### ISSUE TITLE
After php artisan down cant access the niceartisan

### ISSUE THREAD

**Issue by adnanmayo** [bestmomo/nice-artisan#4]
Hello this is a realy nice package. once we use php artisan down.....nothing works not even niceartisan is there a way to fix it?

**Comment by bestmomo** [comment]
Hello,

When you use **php artisan down** the application is down and **niceartisan** cant work. So the only way to get it back is to use **php artisan up** in console.

**Comment by adnanmayo** [comment]
@bestmomo Thanks for your response i have figured out a way if we simply delete the down file from storage folder application seems to be up and starts working.  I am on shared hosting cant access the terminal. is there a way still around?

**Comment by bestmomo** [comment]
I you set your site down it's because you dont want anyone to access it and niceartisan is a site part. I've made niceartisan to have an easy and cool way to use artisan, mainly on local, not to make a workaround for server without SSH.

So you want a site down for everybody but some administrator keeping access. It's another question. To get it working you must make your own CheckForMaintenanceMode middleware. Look at [this post](http://stackoverflow.com/questions/30752962/laravel-artisan-down-maintenance-mode-except-own-ip) for example.

**Comment by adnanmayo** [comment]
@bestmomo thanks for your help. i think i have found what i was looking for.
